name: Azure Static Web Apps CI/CD

on:

  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      - name: Get Commit Info
        run: |
          commit="${{ github.event.commits[0].message }}"
          function=$(awk 'BEGIN{FS=OFS="|"} {print $1}' <<< ${commit})
          link=$(awk 'BEGIN{FS=OFS="|"} {print $2}' <<< ${commit})

          echo "FUNCTION=$function" >> $GITHUB_ENV
          echo "LINK=$link" >> $GITHUB_ENV

      - name: Show Commit Info
        run: |
          echo "Link: ${{ env.LINK}}"

      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "latest"  # Hugo version: latest OR x.y.z
          extended: true

      - name: Build
        run: hugo

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_STONE_0F92CBF1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          output_location: ''
          app_location: "public" # App source code path
          skip_app_build: true

      - name: Post to Socials
        if: env.FUNCTION == 'PUBLISH' && always()
        id: socials
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.POST_API }}
          method: POST
          contentType: "application/json"
          data: "${{ env.LINK }}"
          timeout: 12000

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "/"
          app_artifact_location: "public"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_STONE_0F92CBF1E }}
          action: "close"
