name: Azure Static Web Apps CI/CD

on:

  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      - name: Get Commit Info
        run: |
          commit="${{ github.event.commits[0].message }}"
          function=$(awk 'BEGIN{FS=OFS="|"} {print $1}' <<< ${commit})
          handle=$(awk 'BEGIN{FS=OFS="|"} {print $2}' <<< ${commit})
          link=$(awk 'BEGIN{FS=OFS="|"} {print $3}' <<< ${commit})
          echo "FUNCTION=$function" >> $GITHUB_ENV
          echo "HANDLE=$handle" >> $GITHUB_ENV
          echo "LINK=$link" >> $GITHUB_ENV
        
      - name: Show Commit Info
        run: |
          echo "Handle: ${{ env.HANDLE}}"
          echo "Link: ${{ env.LINK}}"

      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "latest"  # Hugo version: latest OR x.y.z
          extended: true

      - name: Build
        run: hugo

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_STONE_0F92CBF1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          # api_location: "api" # Api source code path - optional
          app_artifact_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
          
      - uses: ethomson/send-tweet-action@v1
        name: Send Tweet
        if: env.FUNCTION == 'PUBLISH'      
        with:
          status: "Had a great time chatting with ${{ env.HANDLE }} on @CoffeeAndOSS today about all kinds of #tech topics. Video is live on @youtube and podcast is available wherever you find them. Take a look/listen and thanks! ${{ env.LINK }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_STONE_0F92CBF1E }}
          action: "close"
